# Generated by Django 5.0.4 on 2026-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
