# Generated by Django 5.0.4 on 2026-04-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_user_id_d7ba42_idx',
            old_name='payments_tr_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_referen_530efe_idx',
            old_name='payments_tr_referen_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_status_96e6c0_idx',
            old_name='payments_tr_status_idx',
        ),
    ]
